apiVersion: v1
kind: ServiceAccount
metadata:
  name: terraform
secrets:
  - name: terraform-secret
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: terraform
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: terraform
subjects:
  - kind: ServiceAccount
    name: terraform
    namespace: default
roleRef:
  kind: ClusterRole
  name: terraform
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Secret
metadata:
  name: terraform-secret
  annotations:
    kubernetes.io/service-account.name: terraform
type: kubernetes.io/service-account-token
---

